name: Run Tests on Push

on:
  push:
    branches:
      - main  # Trigger for the main branch, adjust as needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify the Node.js version you're using

    - name: Install dependencies
      run: npm install  # Install dependencies with npm, or use `yarn install` if using Yarn

    - name: Ensure Jest is executable
      run: chmod +x ./node_modules/.bin/jest  # Make Jest executable if needed

    - name: Run tests
      run: npx jest  # Run Jest from the local node_modules
