name: Run Tests on Push

on:
  push:
    branches:
      - main  # Trigger for the main branch, adjust as needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify the Node.js version you're using

    - name: Install dependencies
      run: npm install  # Install dependencies with npm, or use `yarn install` if using Yarn

    - name: Run tests
      run: npm test  # Run the test command (for Vite/React, it should be based on the setup)
